--------------------------------------------------------
-- Archivo creado  - sábado-abril-25-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_RADIACION
--------------------------------------------------------

  CREATE TABLE "METEO_ESTRELLA"."FACT_RADIACION" 
   (	"ID_CIUDAD" NUMBER(*,0), 
	"ID_TIEMPO" NUMBER(*,0), 
	"INDICE_UV" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into METEO_ESTRELLA.FACT_RADIACION
SET DEFINE OFF;
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('2','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('32','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('3','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('33','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('4','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('34','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('5','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('35','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('6','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('36','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('7','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('37','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('8','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('38','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('9','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('39','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('10','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('40','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('11','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('41','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('12','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('42','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('13','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('43','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('14','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('44','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('15','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('45','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('16','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('46','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('17','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('47','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('18','1','8');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('48','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('19','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('49','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('20','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('50','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('21','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('51','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('22','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('52','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('23','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('53','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('24','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('54','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('25','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('55','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('26','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('56','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('27','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('57','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('28','1','7');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('58','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('29','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('59','1','9');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('30','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('60','1','6');
Insert into METEO_ESTRELLA.FACT_RADIACION (ID_CIUDAD,ID_TIEMPO,INDICE_UV) values ('31','1','6');
